ajout des smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -303,36 +303,43 @@ jobs:
             cd .circleci/ansible
             ansible-playbook -i inventory.txt deploy-backend.yml 
         
-  # smoke-test:
-  #   docker:
-  #     - image: cimg/base:stable 
-  #   steps:
-  #     - checkout
-  #     - install_awscli
-  #     - install_nodejs
-  #     - run:
-  #         name: Backend Smoke test
-  #         command: |
-  #           BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-  #             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-  #             --output text) 
-  #           echo "IP ---> ${BACKEND_PUBLIC_IP}"
-  #           echo "API_URL ---> http://${BACKEND_PUBLIC_IP}:3030"
-  #           export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-  #           if curl -s $API_URL/api/status | grep "ok"
-  #           then
-  #             echo "Backend smoke test successful"
-  #             exit 0
-  #           else
-  #             echo "Backend smoke test failed"
-  #             exit 1
-  #           fi
+  smoke-test:
+    docker:
+      - image: cimg/base:stable 
+    steps:
+      - checkout
+      - install_awscli
+      - install_nodejs
+      - run:
+          name: Backend Smoke test
+          command: |
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --output text) 
+            echo "IP ---> ${BACKEND_PUBLIC_IP}"
+            echo "API_URL ---> http://${BACKEND_PUBLIC_IP}:3030"
+            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then
+              echo "Backend smoke test successful"
+              exit 0
+            else
+              echo "Backend smoke test failed"
+              exit 1
+            fi
       
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           # your code here
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              exit 0
+            else 
+              echo "Frontend smoke test failed"
+              exit 1
+            fi
       # Here's where you will add some code to rollback on failure  
 
 #   cloudfront-update:
@@ -415,8 +422,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       
       # - cloudfront-update:
       #     requires: [smoke-test]
