ajout du fingerprint

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -246,74 +246,105 @@ jobs:
 #             exit 1
 #      # Here's where you will add some code to rollback on failure      
 
-#   deploy-frontend:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#             export API_URL="http://${BACKEND_IP}:3030"
-#             echo "${API_URL}"
-#       - run:
-#           name: Deploy frontend objects
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure      
-                    
-#   deploy-backend:
-#     docker:
-#       # Docker image here that supports Ansible
-#     steps:
-#       # Checkout code from git
-#       # Add ssh keys with fingerprint
-#       # attach workspace
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Deploy backend
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
-
-  smoke-test:
+  deploy-frontend:
     docker:
       - image: cimg/base:stable 
     steps:
       - checkout
       - install_awscli
       - install_nodejs
+      - restore_cache:
+          keys: [frontend-build]
       - run:
-          name: Backend Smoke test
+          name: Install dependencies
+          command: |
+            cd frontend
+            npm install
+      - run:
+          name: Get backend url
           command: |
             BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
               --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text) 
-            echo "IP ---> ${BACKEND_PUBLIC_IP}"
-            echo "API_URL ---> http://${BACKEND_PUBLIC_IP}:3030"
-            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-            if curl -s $API_URL/api/status | grep "ok"
-            then
-              echo "Backend smoke test successful"
-              exit 0
-            else
-              echo "Backend smoke test failed"
-              exit 1
-            fi
-      
+              --output text)
+            echo "API_URL=http://${BACKEND_PUBLIC_IP}:3030" >> frontend/.env
+            cat frontend/.env
       - run:
-          name: Frontend smoke test.
+          name: Deploy frontend objects
           command: |
-            # your code here
+            cd frontend
+            npm run build
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive    
+                    
+          
+  deploy-backend:
+    docker:
+      - image: cimg/base:stable 
+    steps:
+      - checkout
+      - install_awscli
+      - install_ansible 
+      - install_nodejs
+      - add_ssh_keys:
+          fingerprints: ["42:99:42:e4:09:d5:ca:91:e6:a9:78:44:34:c6:7a:13"] 
+      - attach_workspace:
+          at: ~/
+      - restore_cache:
+          keys: [backend-build] 
+      - run:
+          name: Install dependencies
+          command: |
+            cd backend
+            npm i 
+      - run:
+          name: Package Backend
+          command: |
+            cd backend
+            npm run build 
+            ls -l
+            tar -czf artifact.tar.gz dist/* package*
+            ls -l 
+            cd ..
+            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+      - run:
+          name: Deploy backend
+          command: | 
+            export TYPEORM_MIGRATIONS_DIR=./migrations 
+            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+            export TYPEORM_MIGRATIONS=./migrations/*.ts
+            cd .circleci/ansible
+            ansible-playbook -i inventory.txt deploy-backend.yml 
+        
+  # smoke-test:
+  #   docker:
+  #     - image: cimg/base:stable 
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - install_nodejs
+  #     - run:
+  #         name: Backend Smoke test
+  #         command: |
+  #           BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+  #             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #             --output text) 
+  #           echo "IP ---> ${BACKEND_PUBLIC_IP}"
+  #           echo "API_URL ---> http://${BACKEND_PUBLIC_IP}:3030"
+  #           export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+  #           if curl -s $API_URL/api/status | grep "ok"
+  #           then
+  #             echo "Backend smoke test successful"
+  #             exit 0
+  #           else
+  #             echo "Backend smoke test failed"
+  #             exit 1
+  #           fi
+      
+  #     - run:
+  #         name: Frontend smoke test.
+  #         command: |
+  #           # your code here
       # Here's where you will add some code to rollback on failure  
 
 #   cloudfront-update:
